/**
 * @fileoverview gRPC-Web generated client stub for grpc.address
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.20.0
// source: ChatService.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as ChatService_pb from './ChatService_pb';


export class MessageServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptormessage = new grpcWeb.MethodDescriptor(
    '/grpc.address.MessageService/message',
    grpcWeb.MethodType.UNARY,
    ChatService_pb.MessageRequest,
    ChatService_pb.MessageResponse,
    (request: ChatService_pb.MessageRequest) => {
      return request.serializeBinary();
    },
    ChatService_pb.MessageResponse.deserializeBinary
  );

  message(
    request: ChatService_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null): Promise<ChatService_pb.MessageResponse>;

  message(
    request: ChatService_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: ChatService_pb.MessageResponse) => void): grpcWeb.ClientReadableStream<ChatService_pb.MessageResponse>;

  message(
    request: ChatService_pb.MessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: ChatService_pb.MessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/grpc.address.MessageService/message',
        request,
        metadata || {},
        this.methodDescriptormessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/grpc.address.MessageService/message',
    request,
    metadata || {},
    this.methodDescriptormessage);
  }

}

